### ISSUE TITLE
应该是评价时获取图片报错，以及另外一个获取我的评价页面报错

### ISSUE THREAD

**Issue by EvilDrag0n** [6dylan6/auto_comment#38]
HTTPSConnectionPool(host='club.jd.com', port=443): Max retries exceeded with url: /discussion/getProductPageImageCommentList.action?productId=100047365108 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

HTTPSConnectionPool(host='club.jd.com', port=443): Max retries exceeded with url: /myJdcomments/myJdcomment.action (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
Traceback (most recent call last):
  File "/ql/data/scripts/6dylan6_auto_comment/jd_comment.py", line 736, in <module>
    main(opts)
  File "/ql/data/scripts/6dylan6_auto_comment/jd_comment.py", line 572, in main
    N = No(opts)
  File "/ql/data/scripts/6dylan6_auto_comment/jd_comment.py", line 554, in No
    s = '----'.join(['{} {}'.format(i, N[i]) for i in N])
TypeError: 'NoneType' object is not iterable

**Comment by EvilDrag0n** [comment]
哦，是`urllib3`版本出的问题。降低`urllib3`版本至`1.25.11`就可以了。
如果青龙是直接安装到服务器的直接运行就行，如果是用docker安装的，就先进入docker容器后再执行；
进入docker容器`docker exec -it xxxx  bash`  xxx替换成自己的容器id或者容器名
`pip install urllib3==1.25.11`

**Comment by 6dylan6** [comment]
谢谢反馈，我安装指定版本
