### ISSUE TITLE
现在晒单的图片都会说异常

### ISSUE THREAD

**Issue by tufeikafei** [6dylan6/auto_comment#64]
如题，今天我测试评价，发现晒单的图片里面 都是审核不通过，图片之类的都ok，我怀疑是 图片路径识别到过老的图片导致的？
怀疑京东启动了 评价图片路径筛选或者加了一定规则，要么后面通过先下载图片，然后通过：https://club.jd.com/myJdcomments/ajaxUploadImage.action
这个方式 上传图片，然后再进行针对新的评价图片路径进行上传试试？

正在搜集第1个商品第1页的评论信息
正在搜集 京东小家电全面保修5年-K 的好评信息
正在搜集第1个商品第2页的评论信息
正在搜集 京东小家电全面保修5年-K 的好评信息
正在搜集第1个商品第3页的评论信息
正在搜集 京东小家电全面保修5年-K 的好评信息
正在搜集第2个商品第1页的评论信息
本页无评价数据，跳过
正在搜集第3个商品第1页的评论信息
本页无评价数据，跳过
已搜集30条好评信息
评价信息：5星  第一次买扫地机器人，很智能，很灵活，比自己扫得干净，又轻松，省事，真的不错，值得购买！星好评！电器就买京东，因为京东有专业的售后保障。小家电一般只保障一年。整体都很好，颜值不错，比前几代都要好看一点。宝贝已经用了几天了。
图片：//img30.360buyimg.com/shaidan/jfs/t1/237173/34/22504/28200/668b956cFa29beb15/b36a5938dd6de9ca.jpg,//img30.360buyimg.com/shaidan/jfs/t1/221517/2/34098/106229/6555fb20F72335506/4b8075e96df15416.jpg

**Comment by amudream** [comment]
+1，能不能加个图片二次处理，比如裁剪或者缩放等

**Comment by tufeikafei** [comment]
可以通过下载图片 然后再进行上传 ，裁减可能比较麻烦。
image原来的路径里面包含各种用户信息等，通过下载 再上传的方式理论上可行，就是有个 phpsession 这个怎么取？

**Comment by sparkssssssss** [comment]
> 可以通过下载图片 然后再进行上传 ，裁减可能比较麻烦。 image原来的路径里面包含各种用户信息等，通过下载 再上传的方式理论上可行，就是有个 phpsession 这个怎么取？

请问楼主解决了上传的问题了嘛
